display/config/routes.rb
Display::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions', :confirmations => 'confirmations', :passwords => 'passwords'}, :defaults => { :org_name => nil }

  devise_scope(:user) do
    get    'registrations/lookup', :to => 'registrations#lookup',  :as => 'user_lookup', :defaults => { :org_name => nil }
    delete 'registration/:id',     :to => 'registrations#destroy', :as => 'delete_user', :defaults => { :org_name => nil }
  end

  match '*x', :via => 'OPTIONS', :to => 'application#cors_options'

  get '/status/ecv' => 'status#ecv'

  get '/error' => 'welcome#error', :as => :error_redirect
  get '/not_found_error' => 'welcome#not_found_error', :as => :not_found

  get 'users/:id' => 'organization/users#show', :as => 'user'
  match '/auth/:provider/callback' => 'authentications#create', :via => [:get, :post]

  get 'r/ns'                                => 'redirect#ns',          :as => 'redirect_ns'
  get 'r/ns/:path'                          => 'redirect#ns', :constraints => {:path => /[a-zA-Z0-9\-]+(\/[a-zA-Z0-9\-]+)+\/?/}
  get 'r/:id'                               => 'redirect#ci'
  get 'r/ci/:id'                            => 'redirect#ci',          :as => 'redirect_ci'
  get 'r/release/:id'                       => 'redirect#release'
  get 'r/r/:id'                             => 'redirect#release',     :as => 'redirect_release'
  get 'r/deployment/:id'                    => 'redirect#deployment'
  get 'r/d/:id'                             => 'redirect#deployment',  :as => 'redirect_deployment'
  get 'r/procedure/:id'                     => 'redirect#procedure'
  get 'r/p/:id'                             => 'redirect#procedure',   :as => 'redirect_procedure'
  get 'r/instances/:id'                     => 'redirect#instance'
  get 'r/i/:id'                             => 'redirect#instance',    :as => 'redirect_instance'
  get 'r/instances/:id/monitors/:monitor/d' => 'redirect#monitor_doc', :as => 'redirect_instance_monitor_doc'
  get 'r/:id'                               => 'redirect#ci', :constraints => {:id => /\d+/}

  get 'l/ci/:id'                  => 'lookup#ci',         :as => 'lookup_ci'
  get 'l/ci/:id/:attribute_name'  => 'lookup#ci',         :as => 'lookup_ci_attribute'
  get 'l/rel/:id'                 => 'lookup#relation',   :as => 'lookup_relation'
  get 'l/rel/:id/:attribute_name' => 'lookup#relation',   :as => 'lookup_relation_attribute'
  get 'l/release/:id'             => 'lookup#release'
  get 'l/r/:id'                   => 'lookup#release',    :as => 'lookup_release'
  get 'l/deployment/:id'          => 'lookup#deployment'
  get 'l/d/:id'                   => 'lookup#deployment', :as => 'lookup_deployment'
  get 'l/procedure/:id'           => 'lookup#procedure'
  get 'l/p/:id'                   => 'lookup#procedure',  :as => 'lookup_procedure'
  get 'l/:id(/:attribute_name)'   => 'lookup#ci', :constraints => {:id => /\d+/}

  get '/api_docs' => 'welcome#api_docs'

  resource :support, :controller => 'support', :only => [:show], :defaults => { :org_name => nil } do
    collection do
      get  'announcements'
      put  'announcements'
      get  'compute_report'
      get  'compute'
      post 'compute'
      get  'search'
      get  'organizations'
      get  'users'
      get  'users/:id' => 'support#user'
      get  'user'
      get  'groups'
      get  'groups/:id' => 'support#group'
      get  'group'
      get  'global_admins'
      get  'cost'
      get  'deployment_to_all_primary_check'
      put  'deployment_to_all_primary_check'
      get  'cloud_supports'
      put  'cloud_supports'

      get 'organization/:name', :action => 'organization', :as => 'organization'
    end
  end

  resource :metadata, :controller => 'metadata', :only => [:show] do
    collection do
      get 'lookup_class_name'
      get 'lookup_attr_name'
    end
  end

  resource :watch, :controller => 'watch', :only => [:show, :create, :destroy]

  post '/:org_name/request_access' => 'organization#request_access', :as => 'organization_request_access'
  get '/:org_name' => 'organization#public_profile', :as => 'organization_public_profile'

  resource :organization, :controller => 'organization', :only => :none do
    get 'announcement', :on => :collection
    put 'announcement', :on => :collection
    get 'lookup',       :on => :collection
  end

  namespace :account, :defaults => { :org_name => nil } do
    resource :profile, :controller => 'profile', :only => [:show, :update] do
      member do
        put  'change_password'
        put  'hide_wizard'
        put  'change_organization'
        put  'reset_authentication_token'
        get  'show_eula'
        put  'accept_eula'
        post 'authentication_token'
        get  'organizations'
        put  'session_preferences'
      end
    end

    resources :favorites, :controller => 'favorites', :only => [:index, :show, :destroy]

    resources :organizations, :only => [:index, :show, :new, :create, :destroy] do
      get    'current_organization', :on => :collection
      delete 'leave', :on => :member
    end

    resources :groups do
      get 'confirm_delete', :on => :member
      get 'lookup', :on => :collection

      resources :members, :controller => 'group_members', :as => 'members', :only => [:index, :show, :create, :update, :destroy]
    end
  end

  resources :authentications, :only => [:create, :destroy]

  resources :clouds, :controller => 'cloud/clouds', :only => :none do
    collection do
      get :services
      get :offerings
    end
  end

  scope '/:org_name' do
    resource :organization, :controller => 'organization', :only => [:show, :edit, :update] do
      member do
        get 'notifications'
        get 'deployments'
        get 'procedures'
        get 'reports'
        get 'health'
        get 'search'
        get 'cost_rate'
        get 'cost'
      end

      resources :users, :controller => 'organization/users' do
        collection do
          post 'confirm_remove'
          delete 'remove'
        end
      end

      resources :teams, :controller => 'organization/teams' do
        resources :members, :controller => 'organization/team_members', :as => :members, :only => [:index, :create, :destroy]
      end

      resources :environments, :controller => 'organization/environments'
      resources :policies, :controller => 'organization/policies' do
        get 'evaluate', :on => :collection
        get 'evaluate', :on => :member
      end
    end

    resources :notifications

    resource :watch, :controller => 'watch', :only => [:create, :destroy]
    resources :favorites, :controller => 'account/favorites', :only => [:show, :create, :destroy]

    resource :lookup, :controller => 'lookup', :only => :none do
      get 'counterparts', :on => :collection
      get 'variables', :on => :collection
      get 'ci_lookup', :on => :collection
    end

    resource :ci, :controller => 'lookup', :only => :none do
      post 'policy_violations', :on => :collection
    end

    resources :services, :controller => 'services/services' do
      get :available, :on => :collection
    end

    resources :clouds, :controller => 'cloud/clouds' do
      collection do
        get :locations
        get :services
        get :offerings
      end

      member do
        get :operations
        get :instances
        get :procedures
        get :reports
        get :search
        get :teams
        put :update_teams
      end

      resources :zones, :controller => 'cloud/zones' do
        resources :services, :controller => 'cloud/services'
      end

      resources :services, :controller => 'cloud/services' do
        get :available, :on => :collection
        get :diff, :on => :collection

        resources :offerings, :controller => 'cloud/offerings' do
          get 'available', :on => :collection
        end
      end

      resources :compliances, :controller => 'cloud/compliances' do
        get :available, :on => :collection
      end

      resources :supports, :controller => 'cloud/supports'

      resources :variables, :controller => 'cloud/variables'
    end

    resources :reports, :only => :none do
      get  'compute',      :on => :collection
      post 'compute',      :on => :collection
      get  'health',       :on => :collection
      get  'notification', :on => :collection
      get  'cost',         :on => :collection
    end

    resources :packs, :controller => 'catalog/packs', :only => [:index]

    resource :catalog, :controller => 'catalog', :only => [:show]

    namespace :catalog do
      resources :designs, :only => [:index, :show, :destroy] do
        get  'export',  :on => :member
        post 'import',  :on => :collection
        get  'diagram', :on => :member

        resources :variables, :only => [:index, :show]

        resources :platforms, :only => [:index, :show] do
          get 'diagram', :on => :member

          resources :variables, :controller => 'local_variables', :only => [:index, :show]

          resources :components, :only => [:index, :show] do
            resources :attachments, :only => [:index, :show]
            resources :monitors, :only => [:index, :show] do
              get 'watched_by', :on => :member
            end
          end

          resources :monitors, :only => [:show] do
            get 'watched_by', :on => :member
          end
        end
      end

      resources :packs, :only => [:index] do
        get 'versions', :on => :collection
      end

      scope '/packs/:source/:pack(/:version)(/:availability)',
            :as => 'pack',
            :constraints => {:version => /\d+(\.\d+(\.\d+)?)?/,
                             :availability => /single|redundant/} do
        get ''                      => 'packs#show',       :as => ''
        put ''                      => 'packs#update',     :as => 'update'
        get 'versions'              => 'packs#versions',   :as => 'versions'

display/app/views/lookup/_counterparts.html.erb
<% groups           = [{:items => []}]
   current_dto      = params[:dto_area]
   ci_name          = @ci.ciName
   ci_class_name    = @ci.ciClassName
   ci_ns_path_split = @ci.nsPath.split('/')
   assembly         = ci_ns_path_split[2]
   env              = ci_ns_path_split[3]
   if target_dto == 'design'
     groups[0][:items] << link_to(icon('arrow-circle-up', 'top of design'), assembly_design_path(assembly))
     if ci_class_name == 'catalog.Platform'
       items = @counterparts.inject([]) do |a, c|
         a << link_to(c.ciName, path_to_ci(c)) if c.ciId != @ci.ciId && c.ciClassName.start_with?('catalog.')
         a
       end
       groups << {:title => 'Other platforms', :items => items} if items.present?
     elsif ci_class_name.start_with?('catalog.')
       items = @counterparts.inject([]) do |a, c|
         a << link_to(c.nsPath.split('/').last, path_to_ci(c)) if c.ciId != @ci.ciId && c.ciClassName.start_with?('catalog.')
         a
       end
       groups << {:title => "#{content_tag(:strong, ci_name)} in", :items => items} if items.present?
     elsif ci_class_name.end_with?('.Environment')
     elsif ci_class_name.end_with?('.Platform')
       groups[0][:items] << link_to(raw("#{icon('arrow-circle-left')} #{content_tag(:strong, ci_name)} platform"), assembly_design_platform_path(assembly, ci_name))
     else
       groups[0][:items] << link_to(raw("#{icon('arrow-circle-left')} #{content_tag(:strong, ci_name)} component"), edit_assembly_design_platform_component_path(assembly, ci_ns_path_split[5], ci_name, :class_name => ci_class_name.split('.').last))
     end
   else
     if target_dto == 'transition'
       groups[0][:items] << link_to(icon('arrow-circle-up', 'top of transition'), assembly_transition_path(assembly))
     elsif target_dto == 'operations'
       groups[0][:items] << link_to(icon('arrow-circle-up', 'top of operations'), assembly_operations_path(assembly))
     end

     if ci_class_name == 'manifest.Environment'
       groups[0][:items] << link_to(raw("#{icon("arrow-circle-#{current_dto == 'operations' ? 'left' : 'right'}")} #{content_tag(:strong, ci_name)} environment"), path_to_ci(@ci, target_dto)) unless target_dto == current_dto

       items = @counterparts.inject([]) do |a, c|
         a << link_to(c.ciName, path_to_ci(c, target_dto)) unless c.ciId == @ci.ciId
         a
       end
       groups << {:title => 'Other environments', :items => items} if items.present?
     elsif ci_class_name == 'catalog.Platform'
       @counterparts.group_by { |c| c.ciAttributes.major_version }.to_a.sort_by { |c| c.first }.each do |ver, cc|
         items = cc.inject([]) do |a, c|
           ns_path_split = c.nsPath.split('/')
           a << link_to(ns_path_split[3], path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && c.ciName == ci_name && ns_path_split[4] == 'manifest'
           a
         end
         groups << {:title => "#{content_tag(:strong, ci_name)} <small class='muted'>ver.#{ver}</small> in environment", :items => items} if items.present?
       end
     elsif ci_class_name == 'manifest.Platform'
       groups[0][:items] << link_to(raw("#{icon("arrow-circle-#{current_dto == 'operations' ? 'left' : 'right'}")} #{content_tag(:strong, ci_name)} platform"), path_to_ci(@ci, target_dto)) unless target_dto == current_dto

       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[3]}/#{ci_name} <small class='muted'>ver.#{c.ciAttributes.major_version}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && c.ciName == ci_name
         a
       end
       groups << {:title => "#{content_tag(:strong, ci_name)} platform in other environments", :items => items} if items.present?

       items = @counterparts.inject([]) do |a, c|
         a << link_to(raw("#{c.ciName} <small class='muted'>ver.#{c.ciAttributes.major_version}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && c.nsPath.split('/')[3] == env
         a
       end
       groups << {:title => 'Other platforms in this environment', :items => items} if items.present?
     elsif ci_class_name.start_with?('catalog.')
       platform = ci_ns_path_split[4]
       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[3]}/#{platform} <small class='muted'>ver.#{ns_path_split[6]}</small>"), path_to_ci(c, target_dto)) if ns_path_split[4] == 'manifest' && ns_path_split[5] == platform
         a
       end
       groups << {:title => "#{content_tag(:strong, ci_name)} in", :items => items} if items.present?
     elsif ci_class_name.start_with?('manifest.')
       groups[0][:items] << link_to(raw("#{icon("arrow-circle-#{current_dto == 'operations' ? 'left' : 'right'}")} #{content_tag(:strong, ci_name)} component"), path_to_ci(@ci, target_dto)) unless target_dto == current_dto

       platform = ci_ns_path_split[5]
       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[3]}/#{ns_path_split[5]} <small class='muted'>ver.#{ns_path_split[6]}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && ns_path_split[5] == platform
         a
       end
       groups << {:title => "#{content_tag(:strong, ci_name)} component in other environments", :items => items} if items.present?

       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[5]} <small class='muted'>ver.#{ns_path_split[6]}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && ns_path_split[3] == env
         a
       end
       groups << {:title => "#{content_tag(:strong, ci_name)} component in other platforms", :items => items} if items.present?
     end
   end
%>
<% if groups.present? %>
  <% groups.each do |g| %>
    <% items = g[:items] %>
    <% if items.present? %>
      <% title = g[:title] %>
      <% if title.present? %>
        <li class="disabled title">
          <%= link_to_function(raw("#{title} #{count_marker(items.size, 'badge-info')}"), '') %>
        </li>
      <% end %>
      <% items.sort.each do |item| %>
        <li><%= raw(item) %></li>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <li class="disabled"><%= link_to_function('no results', '') %></li>
<% end %>

display/app/views/lookup/_policy_violations.html.erb
<% if @violations.nil? %>
  <%= falied_loading_indicator('Failed to check policy compliance') %>
<% elsif @violations.empty? %>
  <%= marker('passed', 'label-success') %>
<% else %>
  <%= marker('failed', 'label-important') %><br/>
  <ul class="unstyled" style="margin-left:10px">
    <% @violations.each do |p| %>
      <li>
        <strong><%= p.ciName %></strong>
        <% desc = p.ciAttributes.description %>
        <% if desc.present? %>
          - <%= desc %>
        <% end %>
        <% doc_url = p.ciAttributes.docurl %>
        <%= link_to(icon('book', 'more...'), doc_url, :target => '_blank') if doc_url.present? %>
      </li>
    <% end %>
  </ul>
<% end %>

display/app/views/lookup/_side_bar_counterparts.html.erb
<% groups           = [{:items => []}]
   ci_name          = @ci.ciName
   ci_class_name    = @ci.ciClassName
   ci_ns_path_split = @ci.nsPath.split('/')
   env              = ci_ns_path_split[3]
   if target_dto == 'design'
     if ci_class_name == 'catalog.Platform'
       items = @counterparts.inject([]) do |a, c|
         a << link_to(c.ciName, path_to_ci(c)) if c.ciId != @ci.ciId && c.ciClassName.start_with?('catalog.')
         a
       end
       groups << {:title => 'Other platforms', :items => items} if items.present?
     elsif ci_class_name.start_with?('catalog.')
       items = @counterparts.inject([]) do |a, c|
         a << link_to(c.nsPath.split('/').last, path_to_ci(c)) if c.ciId != @ci.ciId && c.ciClassName.start_with?('catalog.')
         a
       end
       groups << {:title => "#{context_nav_name_label(ci_name)} component in", :items => items} if items.present?
     end
   else
     if ci_class_name == 'manifest.Environment'
       items = @counterparts.inject([]) do |a, c|
         a << link_to(c.ciName, path_to_ci(c, target_dto)) unless c.ciId == @ci.ciId
         a
       end
       groups << {:title => 'Other environments', :items => items} if items.present?
     elsif ci_class_name == 'catalog.Platform'
       @counterparts.group_by { |c| c.ciAttributes.major_version }.to_a.sort_by { |c| c.first }.each do |ver, cc|
         items = cc.inject([]) do |a, c|
           ns_path_split = c.nsPath.split('/')
           a << link_to(ns_path_split[3], path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && c.ciName == ci_name && ns_path_split[4] == 'manifest'
           a
         end
         groups << {:title => "#{context_nav_name_label(ci_name)} <small class='muted'>ver.#{ver}</small> in environment", :items => items} if items.present?
       end
     elsif ci_class_name == 'manifest.Platform'
       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[3]}/#{ci_name} <small class='muted'>ver.#{c.ciAttributes.major_version}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && c.ciName == ci_name
         a
       end
       groups << {:title => "#{context_nav_name_label(ci_name)} platform in other environments", :items => items} if items.present?

       items = @counterparts.inject([]) do |a, c|
         a << link_to(raw("#{c.ciName} <small class='muted'>ver.#{c.ciAttributes.major_version}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && c.nsPath.split('/')[3] == env
         a
       end
       groups << {:title => 'Other platforms in this environment', :items => items} if items.present?
     elsif ci_class_name.start_with?('catalog.')
       platform = ci_ns_path_split[4]
       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[3]}/#{platform} <small class='muted'>ver.#{ns_path_split[6]}</small>"), path_to_ci(c, target_dto)) if ns_path_split[4] == 'manifest' && ns_path_split[5] == platform
         a
       end
       groups << {:title => "#{context_nav_name_label(ci_name)} in", :items => items} if items.present?
     elsif ci_class_name.start_with?('manifest.')
       platform = ci_ns_path_split[5]
       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[3]}/#{ns_path_split[5]} <small class='muted'>ver.#{ns_path_split[6]}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && ns_path_split[5] == platform
         a
       end
       groups << {:title => "#{context_nav_name_label(ci_name)} component in other environments", :items => items} if items.present?

       items = @counterparts.inject([]) do |a, c|
         ns_path_split = c.nsPath.split('/')
         a << link_to(raw("#{ns_path_split[5]} <small class='muted'>ver.#{ns_path_split[6]}</small>"), path_to_ci(c, target_dto)) if c.ciId != @ci.ciId && ns_path_split[3] == env
         a
       end
       groups << {:title => "#{context_nav_name_label(ci_name)} component in other platforms", :items => items} if items.present?
     end
   end
%>
<% visible_count = 3 %>
<% if groups.present? %>
  <% groups.each do |g| %>
    <% items = g[:items] %>
    <% if items.present? %>
      <% title = g[:title] %>
      <% if title.present? %>
        <li class="indent minor">
          <%= link_to_function(raw("#{icon('caret-down', title)}"), 'toggleSidebarInlineSelectionList(this)') %>
          <ul class="submenu">
            <% items.sort! %>
            <% items[0...visible_count].each do |item| %>
              <li><%= raw(item) %></li>
            <% end %>
            <% if items.size > visible_count %>
              <li><%= link_to_function(content_tag(:strong, '...'), '$j(this).parent().hide().siblings(".hide").show()') %></li>
              <% items[visible_count..-1].each do |item| %>
                <li class="hide"><%= raw(item) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
    <% end %>
  <% end %>
<% else %>
<% end %>

display/app/views/lookup/counterparts.js.erb
<% %w(design transition operations).each do |area| %>
  $j("#app_nav .<%= area %> .dropdown-menu").html("<%= escape_javascript(render('counterparts', :target_dto => area)) %>");
  $j('#app_nav .<%= area %> a.dropdown-toggle').attr('href', '#').removeAttr('data-remote');
  $j(".sidebar ul.menu .<%= area %>.more").replaceWith("<%= escape_javascript(render('lookup/side_bar_counterparts', :target_dto => area).presence || ' ') %>");
<% end %>

display/app/views/lookup/policy_violations.js.erb
$j(".ci-policy-check").html("<%= escape_javascript(render('policy_violations')) %>");