display/config/routes.rb
Display::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions', :confirmations => 'confirmations', :passwords => 'passwords'}, :defaults => { :org_name => nil }

  devise_scope(:user) do
    get    'registrations/lookup', :to => 'registrations#lookup',  :as => 'user_lookup', :defaults => { :org_name => nil }
    delete 'registration/:id',     :to => 'registrations#destroy', :as => 'delete_user', :defaults => { :org_name => nil }
  end

  match '*x', :via => 'OPTIONS', :to => 'application#cors_options'

  get '/status/ecv' => 'status#ecv'

  get '/error' => 'welcome#error', :as => :error_redirect
  get '/not_found_error' => 'welcome#not_found_error', :as => :not_found

  get 'users/:id' => 'organization/users#show', :as => 'user'
  match '/auth/:provider/callback' => 'authentications#create', :via => [:get, :post]

  get 'r/ns'                                => 'redirect#ns',          :as => 'redirect_ns'
  get 'r/ns/:path'                          => 'redirect#ns', :constraints => {:path => /[a-zA-Z0-9\-]+(\/[a-zA-Z0-9\-]+)+\/?/}
  get 'r/:id'                               => 'redirect#ci'
  get 'r/ci/:id'                            => 'redirect#ci',          :as => 'redirect_ci'
  get 'r/release/:id'                       => 'redirect#release'
  get 'r/r/:id'                             => 'redirect#release',     :as => 'redirect_release'
  get 'r/deployment/:id'                    => 'redirect#deployment'
  get 'r/d/:id'                             => 'redirect#deployment',  :as => 'redirect_deployment'
  get 'r/procedure/:id'                     => 'redirect#procedure'
  get 'r/p/:id'                             => 'redirect#procedure',   :as => 'redirect_procedure'
  get 'r/instances/:id'                     => 'redirect#instance'
  get 'r/i/:id'                             => 'redirect#instance',    :as => 'redirect_instance'
  get 'r/instances/:id/monitors/:monitor/d' => 'redirect#monitor_doc', :as => 'redirect_instance_monitor_doc'
  get 'r/:id'                               => 'redirect#ci', :constraints => {:id => /\d+/}

  get 'l/ci/:id'                  => 'lookup#ci',         :as => 'lookup_ci'
  get 'l/ci/:id/:attribute_name'  => 'lookup#ci',         :as => 'lookup_ci_attribute'
  get 'l/rel/:id'                 => 'lookup#relation',   :as => 'lookup_relation'
  get 'l/rel/:id/:attribute_name' => 'lookup#relation',   :as => 'lookup_relation_attribute'
  get 'l/release/:id'             => 'lookup#release'
  get 'l/r/:id'                   => 'lookup#release',    :as => 'lookup_release'
  get 'l/deployment/:id'          => 'lookup#deployment'
  get 'l/d/:id'                   => 'lookup#deployment', :as => 'lookup_deployment'
  get 'l/procedure/:id'           => 'lookup#procedure'
  get 'l/p/:id'                   => 'lookup#procedure',  :as => 'lookup_procedure'
  get 'l/:id(/:attribute_name)'   => 'lookup#ci', :constraints => {:id => /\d+/}

  get '/api_docs' => 'welcome#api_docs'

  resource :support, :controller => 'support', :only => [:show], :defaults => { :org_name => nil } do
    collection do
      get  'announcements'
      put  'announcements'
      get  'compute_report'
      get  'compute'
      post 'compute'
      get  'search'
      get  'organizations'
      get  'users'
      get  'users/:id' => 'support#user'
      get  'user'
      get  'groups'
      get  'groups/:id' => 'support#group'
      get  'group'
      get  'global_admins'
      get  'cost'
      get  'deployment_to_all_primary_check'
      put  'deployment_to_all_primary_check'
      get  'cloud_supports'
      put  'cloud_supports'

      get 'organization/:name', :action => 'organization', :as => 'organization'
    end
  end

  resource :metadata, :controller => 'metadata', :only => [:show] do
    collection do
      get 'lookup_class_name'
      get 'lookup_attr_name'
    end
  end

  resource :watch, :controller => 'watch', :only => [:show, :create, :destroy]

  post '/:org_name/request_access' => 'organization#request_access', :as => 'organization_request_access'
  get '/:org_name' => 'organization#public_profile', :as => 'organization_public_profile'

  resource :organization, :controller => 'organization', :only => :none do
    get 'announcement', :on => :collection
    put 'announcement', :on => :collection
    get 'lookup',       :on => :collection
  end

  namespace :account, :defaults => { :org_name => nil } do
    resource :profile, :controller => 'profile', :only => [:show, :update] do
      member do
        put  'change_password'
        put  'hide_wizard'
        put  'change_organization'
        put  'reset_authentication_token'
        get  'show_eula'
        put  'accept_eula'
        post 'authentication_token'
        get  'organizations'
        put  'session_preferences'
      end
    end

    resources :favorites, :controller => 'favorites', :only => [:index, :show, :destroy]

    resources :organizations, :only => [:index, :show, :new, :create, :destroy] do
      get    'current_organization', :on => :collection
      delete 'leave', :on => :member
    end

    resources :groups do
      get 'confirm_delete', :on => :member
      get 'lookup', :on => :collection

      resources :members, :controller => 'group_members', :as => 'members', :only => [:index, :show, :create, :update, :destroy]
    end
  end

  resources :authentications, :only => [:create, :destroy]

  resources :clouds, :controller => 'cloud/clouds', :only => :none do
    collection do
      get :services
      get :offerings
    end
  end

  scope '/:org_name' do
    resource :organization, :controller => 'organization', :only => [:show, :edit, :update] do
      member do
        get 'notifications'
        get 'deployments'
        get 'procedures'
        get 'reports'
        get 'health'
        get 'search'
        get 'cost_rate'
        get 'cost'
      end

      resources :users, :controller => 'organization/users' do
        collection do
          post 'confirm_remove'
          delete 'remove'
        end
      end

      resources :teams, :controller => 'organization/teams' do
        resources :members, :controller => 'organization/team_members', :as => :members, :only => [:index, :create, :destroy]
      end

      resources :environments, :controller => 'organization/environments'
      resources :policies, :controller => 'organization/policies' do
        get 'evaluate', :on => :collection
        get 'evaluate', :on => :member
      end
    end

    resources :notifications

    resource :watch, :controller => 'watch', :only => [:create, :destroy]
    resources :favorites, :controller => 'account/favorites', :only => [:show, :create, :destroy]

    resource :lookup, :controller => 'lookup', :only => :none do
      get 'counterparts', :on => :collection
      get 'variables', :on => :collection
      get 'ci_lookup', :on => :collection
    end

    resource :ci, :controller => 'lookup', :only => :none do
      post 'policy_violations', :on => :collection
    end

    resources :services, :controller => 'services/services' do
      get :available, :on => :collection
    end

    resources :clouds, :controller => 'cloud/clouds' do
      collection do
        get :locations
        get :services
        get :offerings
      end

      member do
        get :operations
        get :instances
        get :procedures
        get :reports
        get :search
        get :teams
        put :update_teams
      end

      resources :zones, :controller => 'cloud/zones' do
        resources :services, :controller => 'cloud/services'
      end

      resources :services, :controller => 'cloud/services' do
        get :available, :on => :collection
        get :diff, :on => :collection

        resources :offerings, :controller => 'cloud/offerings' do
          get 'available', :on => :collection
        end
      end

      resources :compliances, :controller => 'cloud/compliances' do
        get :available, :on => :collection
      end

      resources :supports, :controller => 'cloud/supports'

      resources :variables, :controller => 'cloud/variables'
    end

    resources :reports, :only => :none do
      get  'compute',      :on => :collection
      post 'compute',      :on => :collection
      get  'health',       :on => :collection
      get  'notification', :on => :collection
      get  'cost',         :on => :collection
    end

    resources :packs, :controller => 'catalog/packs', :only => [:index]

    resource :catalog, :controller => 'catalog', :only => [:show]

    namespace :catalog do
      resources :designs, :only => [:index, :show, :destroy] do
        get  'export',  :on => :member
        post 'import',  :on => :collection
        get  'diagram', :on => :member

        resources :variables, :only => [:index, :show]

        resources :platforms, :only => [:index, :show] do
          get 'diagram', :on => :member

          resources :variables, :controller => 'local_variables', :only => [:index, :show]

          resources :components, :only => [:index, :show] do
            resources :attachments, :only => [:index, :show]
            resources :monitors, :only => [:index, :show] do
              get 'watched_by', :on => :member
            end
          end

          resources :monitors, :only => [:show] do
            get 'watched_by', :on => :member
          end
        end
      end

      resources :packs, :only => [:index] do
        get 'versions', :on => :collection
      end

      scope '/packs/:source/:pack(/:version)(/:availability)',
            :as => 'pack',
            :constraints => {:version => /\d+(\.\d+(\.\d+)?)?/,
                             :availability => /single|redundant/} do
        get ''                      => 'packs#show',       :as => ''
        put ''                      => 'packs#update',     :as => 'update'
        get 'versions'              => 'packs#versions',   :as => 'versions'

display/app/controllers/cloud/supports_controller.rb
class Cloud::SupportsController < ApplicationController
  SUPPORT_PERMISSION_CLOUD_SUPPORT_MANAGEMENT = 'cloud_support_management'

  before_filter :find_cloud_and_support
  before_filter :authorize_write, :only => [:new, :create, :update, :destroy]

  def index
    @supports = Cms::Relation.all(:params => {:ciId         => @cloud.ciId,
                                              :direction    => 'from',
                                              :relationName => 'base.SupportedBy'}).map(&:toCi)
    respond_to do |format|
      format.js { render :action => :index }
      format.json { render :json => @supports }
    end
  end

  def show
    render_json_ci_response(@support.present?, @support)
  end

  def new
    @support = Cms::Ci.build(:nsPath => cloud_ns_path(@cloud), :ciClassName => 'cloud.Support')

    respond_to do |format|
      format.js { render :action => :edit }
      format.json { render_json_ci_response(true, @support) }
    end
  end

  def create
    @support = Cms::Ci.build(params[:cms_ci].merge(:ciClassName => 'cloud.Support', :nsPath => cloud_ns_path(@cloud)))
    relation = Cms::Relation.build(:nsPath       => cloud_ns_path(@cloud),
                                   :relationName => 'base.SupportedBy',
                                   :fromCiId     => @cloud.ciId,
                                   :toCi         => @support)
    ok       = execute_nested(@support, relation, :save)
    @support = relation.fromCi if ok

    respond_to do |format|
      format.js { ok ? index : render(:action => :edit) }
      format.json { render_json_ci_response(ok, @support) }
    end
  end

  def update
    ok = execute(@support, :update_attributes, params[:cms_ci])

    respond_to do |format|
      format.js { ok ? index : render(:action => :edit) }
      format.json { render_json_ci_response(ok, @support) }
    end
  end

  def destroy
    ok = execute(@support, :destroy)

    respond_to do |format|
      format.js { ok ? index : render(:action => :edit) }
      format.json { render_json_ci_response(ok, @support) }
    end
  end


  private

  def find_cloud_and_support
    @cloud     = locate_cloud(params[:cloud_id])
    support_id = params[:id]
    @support   = Cms::Ci.locate(support_id, cloud_ns_path(@cloud)) if support_id.present?
  end

  def authorize_write
    unauthorized unless @cloud && has_cloud_support?(@cloud.ciId) && has_support_permission?(SUPPORT_PERMISSION_CLOUD_SUPPORT_MANAGEMENT)
  end
end

display/app/views/support/_announcements_content.html.erb
<div class="control-group">
  <%= label_tag 'document[notice]', 'Notice', :class => 'control-label' %>
  <div class="controls">
    <%= text_area_tag 'document[notice]', resource.document[:notice], :class => 'input-xlarge text', :rows => 15 %>
  </div>
</div>
<div class="control-group">
  <%= label_tag 'document[critical]', 'Critical', :class => 'control-label' %>
  <div class="controls">
    <%= text_area_tag 'document[critical]', resource.document[:critical], :class => 'input-xlarge text', :rows => 15 %>
  </div>
</div>

display/app/views/support/_cloud_support_list.html.erb
<%= ci_list(@supports,
            :toolbar => {:sort_by       => [%w(Name ciName), %w(Created created), %w(Org org), %w(Status status)],
                         :filter_by     => %w(ciName org cloud status),
                         :quick_filters => [{:label => 'All', :value => '', :selected => true},
                                            {:label => 'Enabled', :value => 'status=enabled'},
                                            {:label => 'Disabled', :value => 'status=disabled'}]},
            :menu    => [{:id => 'enable', :label => 'Enable', :url => cloud_supports_support_path,  :method => :put, :param_name => 'enableCiIds', :busy => true},
                         {:id => 'disable', :label => 'Disable', :url => cloud_supports_support_path, :method => :put, :param_name => 'disableCiIds', :busy => true}]) do |builder, target| %>
  <% _, org, _, cloud = target.nsPath.split('/')
     enabled = target.ciAttributes.enabled == 'true' %>
  <% builder.attributes %(ciName="#{target.ciName}" created="#{target.created}" org="#{org}" cloud="#{cloud}" status="#{enabled ? 'enabled' : 'disabled'}") %>
  <% builder.target link_to('', path_to_ci(target), :target => '_blank') %>
  <% builder.icon :none %>
  <% builder.top do %>
    <span class="topname"><%= target.ciName %></span>
    <span class="topdesc"><%= org %>/<%= cloud %></span>
  <% end %>
  <% builder.middle target.ciAttributes.description %>
  <% builder.menu do %>
    <%= link_busy enabled ? icon('toggle-off', 'Disable') : icon('toggle-on', 'Enable'),
                  {:url          => cloud_supports_support_path,
                   :method       => :put,
                   :with         => "'#{enabled ? 'enableCiIds[]' : 'disableCiIds[]'}=#{target.ciId}'",
                   :title        => (enabled ? 'Disable' : 'Enable'),
                   :disable_with => 'wait...',
                   :remote       => true} %>
  <% end %>
  <% builder.status do %>
    <% status = target.ciAttributes.enabled == 'true' ? 'enabled' : 'disabled' %>
    <%= marker(status, state_to_label(status)) %>
    <%= marker('approval', 'label-info') if target.ciAttributes.approval == 'true' %>
  <% end %>
<% end %>

display/app/views/support/_user_info.html.erb
<% if @user %>
  <%= section_panel 'Info', :width => 'single' do %>
    <dl>
      <dt>ID</dt>
      <dd><%= @user.id %></dd>
      <dt>Name</dt>
      <dd><%= @user.name %></dd>
      <dt>Email</dt>
      <dd><%= @user.email %></dd>
      <dt>Created At</dt>
      <dd><%= time_ago_in_words(@user.created_at) %></dd>
      <dt>Last Sign-in At</dt>
      <dd><%= time_ago_in_words(@user.last_sign_in_at) %></dd>
    </dl>
  <% end %>
  <%= section_panel 'Organizatios & Teams', :width => 'single', :position => 'left' do %>
    <%= grouped_list(@teams, :toolbar => {:sort_by   => nil,
                                          :filter_by => %w(org team)}) do |group_builder, org| %>
      <% items = org[:items] %>
      <% group_builder.icon ci_class_image_url('account.Organization') %>
      <% org_name = org[:organization]
         group_builder.title org_name %>
      <% group_builder.menu do %>
        <span class="label label-count"><%= items.size %></span>
      <% end %>
      <%= group_builder.items(items.sort_by(&:name)) do |item_builder, team| %>
        <% item_builder.itemid "team_#{team.id}" %>
        <% item_builder.attributes raw(%(org="#{org_name}" team="#{team.name}")) %>
        <% item_builder.top team.name %>
        <% desc = team.description %>
        <% item_builder.middle desc if desc.present? %>
      <% end %>
    <% end %>
  <% end %>
  <%= section_panel 'Groups', :width => 'single' do %>
    <%= list(@groups,
             :toolbar  => {:list_name => 'group_list',
                           :sort_by   => [%w(Name name), %w(Created created)],
                           :filter_by => %w(name)}) do |builder, group| %>
      <% group_admin = group.admin? %>
      <% builder.itemid "group_#{group.id}" %>
      <% builder.attributes raw(%(name="#{group.name}" created="#{group.created_at}")) %>
      <% builder.top group.name %>
      <% desc = group.description %>
      <% builder.middle desc if desc.present? %>
      <% builder.bottom raw("created #{time_ago_in_words(group.created_at)} by #{group.created_by}") %>
      <% builder.status do %>
        <%= marker('admin', 'label-info') if group_admin %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  User not found.
<% end %>

display/app/views/support/announcements.html.erb
<%= section_panel 'Announcements', :id => 'announcements_section', :width => 'triple', :position => 'left' do %>
  <%= render('announcements') %>
<% end %>

display/app/views/support/announcements.js.erb
$j("#announcements_section .section-content").html("<%= escape_javascript(render('announcements')) %>");
<% if request.put? %>
  $j("#site_announcements").html("<%= escape_javascript(render('layouts/site_announcements', :announcements => @announcements)) %>");
<% end %>

display/app/views/support/cloud_supports.html.erb
<% support_page_header('deployment', 'Deployment Approvals') %>
<%= section_panel 'Cloud Support',
                    :width => 'triple' do %>
  <div id="cloud_support_list">
    <%= render 'cloud_support_list' %>
  </div>
<% end %>

display/app/views/support/cloud_supports.js.erb
$j("#cloud_support_list").html("<%= escape_javascript(render('cloud_support_list')) %>");
hide_modal();

display/app/views/support/compute_report.html.erb
<% support_page_header('compute', 'Compute Report') %>
<%= section_panel 'Compute Report', :width => 'triple', :position => 'left' do %>
  <%= render('base/shared/graph_sunburst',
             :data_url   => compute_support_path,
             :email      => true,
             :table_view => true) %>
<% end %>

display/app/views/support/organization.js.erb
<% if request.delete? %>
  hide_modal();
  <% if @organization.errors.blank? %>
    window.location.reload();
  <% end %>
<% else %>
  <% if @organization %>
    $j("#delete_organization_modal").html("<%= escape_javascript(render('organization')) %>").modal('show');
  <% end %>
<% end %>

display/app/views/support/organizations.html.erb
<%= section_panel 'Organizations',
                  :width => 'triple',
                  :menu  => [link_to_function(icon('search', 'Find organization...'), '$j("#organization_lookup_modal").modal("show")', :class => 'btn btn-mini')] do %>
  <%= list(@organizations,
           :toolbar  => {:sort_by => [%w(Name name), %w(Created created), ['Team User Count', 'team_user_count'], ['Admin User Count', 'admin_count'], ['Admin Group User Count', 'admin_group_user_count']],
                         :filter_by => %w(name owner)}) do |builder, org| %>
    <% builder.itemid org['id'] %>
    <% builder.attributes raw(%(name="#{org['name']}" created="#{org['created_at']}" owner="#{org['owner']}" team_user_count="#{org['team_user_count']}" admin_user_count="#{org['admin_user_count']}" admin_group_user_count="#{org['admin_group_user_count']}")) %>
    <% builder.target link_to('', "/#{org['name']}") %>
    <% builder.top do %>
      <%= org['name'] %>
      <% if org['full_name'].present? %>
        <span class="topdesc"><%= org['full_name'] %></span>
      <% end %>

    <% end %>
    <% builder.middle do %>
      <strong><%= org['team_count'] %></strong> <%= 'team'.pluralize(org['team_count']) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['team_user_count'] %></strong> <%= 'team user'.pluralize(org['team_user_count']) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['group_count'] %></strong> <%= 'group'.pluralize(org['group_count']) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['group_user_count'] %></strong> <%= 'group user'.pluralize(org['group_user_count']) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['admin_user_count'] %></strong> <%= 'admin user'.pluralize(org['admin_user_count']) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['admin_group_count'] %></strong> <%= 'admin group'.pluralize(org['admin_group_count']) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['admin_group_user_count'] %></strong> <%= 'admin group user'.pluralize(org['admin_group_user_count']) %>
      <br/>
      <strong><%= org['assembly_count'] %></strong> <%= 'assembly'.pluralize(org['assembly_count']) %> (<%= org['prod_assembly_count'] %> prod)&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['environment_count'] %></strong> <%= 'environment'.pluralize(org['environment_count']) %> (<%= org['prod_environment_count'] %> prod)&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
      <strong><%= org['compute_count'] %></strong> <%= 'compute'.pluralize(org['compute_count']) %> (<%= org['prod_compute_count'] %> prod)
      <% if org['owner'].present? %>
        &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;<span>owner: <%= org['owner'] %></span>
      <% end %>
    <% end %>
    <% builder.bottom do %>
      created <%= time_ago_in_words(org['created_at']) %>
    <% end %>

    <% builder.menu do %>
      <%= link_to(content_tag(:span, icon('info-circle', 'More...')), organization_support_path(:name => org['name']), :remote => true) %>
    <% end %>
  <% end %>
<% end %>
<div id="delete_organization_modal" class="modal hide"></div>

display/app/views/support/search.html.erb
<% support_page_header('search', 'Global Search') %>
<%= render 'base/search/search' %>

display/app/views/support/show.html.erb
<% title('support')
   app_nav([{:label => 'support', :icon => site_icon(:support), :link => support_path}])
%>
<h2>Support Operations</h2>
<br/>
<% links = []
   links << link_to(icon('bullhorn', 'Announcements',  'fa-fw'), announcements_support_path)  if has_support_permission?('announcement')
   links << link_to(icon('sitemap',  'Organizations',  'fa-fw'), organizations_support_path)  if has_support_permission?('organization')
   links << link_to(icon('user',     'Users',          'fa-fw'), user_support_path)           if has_support_permission?('user')
   links << link_to(icon('group',    'Groups',         'fa-fw'), groups_support_path)          if has_support_permission?('group')

   links << link_to(icon(site_icon(:manages_access), 'Global Admins', 'fa-fw'), global_admins_support_path) if is_global_admin?

   links << link_to(icon(site_icon(:deployment), 'Deployment Approvals', 'fa-fw'), cloud_supports_support_path) if has_support_permission?(Cloud::SupportsController::SUPPORT_PERMISSION_CLOUD_SUPPORT_MANAGEMENT)

   links << link_to(icon('server', 'Compute Report', 'fa-fw'), compute_report_support_path) if has_support_permission?('compute_report')
   if has_support_permission?('cost')
     links << link_to(icon('money', 'Cost Report', 'fa-fw'),
                      cost_support_path(:start_date => Date.today.last_month.beginning_of_month,
                                        :end_date   => Date.today.last_month.end_of_month,
                                        :interval   => 'month',
                                        :tags       => %w(costcenter VP dept pillar)))
   end

   links << link_to(icon('search', 'Search', 'fa-fw'), search_support_path) if has_support_permission?('search') %>
<ul class="support-functions nav nav-tabs nav-stacked">
  <% links.each do |link| %>
    <li><%= link %></li>
  <% end %>
</ul>

display/app/views/support/user.html.erb
<% support_page_header('user', 'Users') %>
<%= section_panel 'User Lookup',
                  :position => 'left',
                  :width    => 'triple' do %>
  <%= form_tag(user_support_url, :remote => true, :method => :get, :class => 'form-inline') do %>
    <%= text_field_tag :id, @user && @user.username, :class => 'input-large', :required => true, :autocomplete => 'off', :placeholder => 'Enter username or id...' %>
    <%= submit_tag 'Show info', :class => 'btn btn-success' %>
  <% end %>
  <hr/>
<% end %>

<div id="user_info">
  <%= render('user_info') if @user %>
</div>

<script>
  var userLookupFn = function (query, process) {
    return $j.get('<%= user_lookup_path %>',
                  {login: query},
                  function (data) {
                    return process(data);
                  });
  };

  var updaterFn = function (item) {
    return item.split(' ')[0];
  };

  $j('input#id').typeahead({source: userLookupFn, updater: updaterFn});
</script>

display/app/views/support/user.js.erb
$j("#user_info").html("<%= escape_javascript(render('user_info')) %>");